# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reverse_pb2 as reverse__pb2


class ReverseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Do = channel.unary_unary(
                '/reverse.Reverse/Do',
                request_serializer=reverse__pb2.Request.SerializeToString,
                response_deserializer=reverse__pb2.Response.FromString,
                )
        self.DoSomething = channel.unary_unary(
                '/reverse.Reverse/DoSomething',
                request_serializer=reverse__pb2.Request.SerializeToString,
                response_deserializer=reverse__pb2.Response.FromString,
                )


class ReverseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Do(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoSomething(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReverseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Do': grpc.unary_unary_rpc_method_handler(
                    servicer.Do,
                    request_deserializer=reverse__pb2.Request.FromString,
                    response_serializer=reverse__pb2.Response.SerializeToString,
            ),
            'DoSomething': grpc.unary_unary_rpc_method_handler(
                    servicer.DoSomething,
                    request_deserializer=reverse__pb2.Request.FromString,
                    response_serializer=reverse__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reverse.Reverse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reverse(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Do(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reverse.Reverse/Do',
            reverse__pb2.Request.SerializeToString,
            reverse__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoSomething(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reverse.Reverse/DoSomething',
            reverse__pb2.Request.SerializeToString,
            reverse__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
