# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreverse.proto\x12\x07reverse\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2l\n\x07Reverse\x12+\n\x02\x44o\x12\x10.reverse.Request\x1a\x11.reverse.Response\"\x00\x12\x34\n\x0b\x44oSomething\x12\x10.reverse.Request\x1a\x11.reverse.Response\"\x00\x42\tZ\x07./protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reverse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _REQUEST._serialized_start=26
  _REQUEST._serialized_end=52
  _RESPONSE._serialized_start=54
  _RESPONSE._serialized_end=81
  _REVERSE._serialized_start=83
  _REVERSE._serialized_end=191
# @@protoc_insertion_point(module_scope)
